name: Rust

on: [push]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/broker_dns && mv target/release/broker_dns target/release/broker_dns_amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/broker_dns_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

